name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Deploy to EC2 Instance
        run: |
          ssh -i "nginx.pem" ubuntu@ec2-18-234-196-207.compute-1.amazonaws.com 'bash -s' < deploy_script.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: devops-intern-assignment-ankush
          
      - name: Update S3 Bucket
        run: |
          aws s3 sync /path/to/static-files s3://devops-intern-assignment-ankush
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

